"""
Renders a filled-out Codebase Intelligence Template (Markdown) for a repository
by querying the knowledge graph for auto-extractable sections and leaving
clearly marked placeholders for the human-authored sections.

Output is designed to be:
  1. Loaded directly into a Claude/Cursor/Codex session as system context
  2. Stored as a living document alongside the repo
  3. Reviewed and completed by the architecture team in the console
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from neo4j import Driver


def render_template(driver: Driver, repo_id: str) -> str:
    sections: list[str] = []
    sections.append(_header(repo_id))
    sections.append(_section_1_identity(driver, repo_id))
    sections.append(_section_2_repo_map(driver, repo_id))
    sections.append(_section_3_adrs(driver, repo_id))
    sections.append(_section_4_glossary(driver, repo_id))
    sections.append(_section_5_invariants(driver, repo_id))
    sections.append(_section_6_data_models(driver, repo_id))
    sections.append(_section_7_api_surface(driver, repo_id))
    sections.append(_section_8_concurrency(driver, repo_id))
    sections.append(_section_9_build(driver, repo_id))
    sections.append(_section_9b_freshness(driver, repo_id))
    sections.append(_section_10_working_style())
    sections.append(_section_11_known_issues(driver, repo_id))
    sections.append(_section_12_pitfalls())
    sections.append(_footer())
    return "\n\n".join(s for s in sections if s)


def _q(driver: Driver, cypher: str, **params) -> list[dict]:
    with driver.session() as s:
        return [dict(r) for r in s.run(cypher, **params)]


# ──────────────────────────────────────────────────────────────────────────────

def _header(repo_id: str) -> str:
    return f"""# Codebase Intelligence: `{repo_id}`
> Auto-generated by CodeKG on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}.
> Sections marked **[HUMAN REQUIRED]** need architecture team input.
> Sections marked **[AUTO]** are derived from static analysis and updated on every commit."""


def _section_1_identity(driver: Driver, repo_id: str) -> str:
    rows = _q(driver,
        "MATCH (r:Repository {repo_id: $rid}) RETURN r",
        rid=repo_id)
    if not rows:
        return ""
    r = rows[0]["r"]

    build_info = _q(driver,
        "MATCH (r:Repository {repo_id: $rid}) RETURN r.build_tool AS build_tool, r.java_version AS java_version, r.description AS description",
        rid=repo_id)
    bi = build_info[0] if build_info else {}

    lines = [
        "## 1. Project Identity  [AUTO]",
        "",
        f"**Name:** {r.get('name', repo_id)}",
    ]
    if bi.get("description"):
        lines.append(f"**One-line purpose:** {bi['description']}")
    else:
        lines.append("**One-line purpose:** <!-- [HUMAN REQUIRED] -->")

    lines += [
        "**Who uses it:** <!-- [HUMAN REQUIRED] -->",
        f"**Root directory:** `{r.get('path', '?')}`",
        f"**Primary language(s):** Java" + (f" {bi['java_version']}" if bi.get("java_version") else ""),
        f"**Build tool:** {bi.get('build_tool', '?')}",
        f"**Last indexed commit:** `{r.get('last_commit', 'not yet indexed')}`",
    ]
    return "\n".join(lines)


def _section_2_repo_map(driver: Driver, repo_id: str) -> str:
    dirs = _q(driver,
        """
        MATCH (d:DirectoryEntry {repo_id: $rid})
        RETURN d.path AS path, d.description AS description, d.package_roots AS package_roots
        ORDER BY d.path
        """,
        rid=repo_id)

    lines = ["## 2. Repository Map  [AUTO]", "", "```"]
    if dirs:
        max_path = max(len(d["path"]) for d in dirs)
        for d in dirs:
            pkg = f"  ({', '.join(d['package_roots'][:2])})" if d.get("package_roots") else ""
            lines.append(f"{d['path']:<{max_path + 2}} — {d['description']}{pkg}")
    else:
        lines.append("<!-- Not yet indexed — run a full scan first -->")
    lines.append("```")

    # Also list top-level packages
    pkgs = _q(driver,
        """
        MATCH (p:Package {repo_id: $rid})
        WHERE NOT p.fqn CONTAINS '.' OR size(split(p.fqn, '.')) <= 2
        RETURN DISTINCT p.fqn AS fqn
        ORDER BY p.fqn
        LIMIT 20
        """,
        rid=repo_id)
    if pkgs:
        lines += ["", "**Top-level packages:**", ""]
        for p in pkgs:
            lines.append(f"- `{p['fqn']}`")

    return "\n".join(lines)


def _section_3_adrs(driver: Driver, repo_id: str) -> str:
    adrs = _q(driver,
        """
        MATCH (adr:ADR {repo_id: $rid})
        RETURN adr ORDER BY adr.adr_id
        """,
        rid=repo_id)

    lines = ["## 3. Architecture Decision Records  [HUMAN REQUIRED]", ""]
    if adrs:
        for row in adrs:
            a = row["adr"]
            lines += [
                f"### {a.get('adr_id', 'ADR-???')}: {a.get('title', 'Untitled')}",
                "",
                f"**Decision:** {a.get('decision', '...')}",
                f"**Alternatives considered:** {a.get('alternatives', '...')}",
                f"**Why:** {a.get('rationale', '...')}",
                f"**Consequences:** {a.get('consequences', '...')}",
                "",
                "---",
                "",
            ]
    else:
        lines += [
            "> No ADRs defined yet. Add them via the Architecture Console.",
            "> ADRs capture the non-obvious decisions that prevent future engineers",
            "> from undoing deliberate choices.",
            "",
            "<!-- Example:",
            "### ADR-001: Why we chose X over Y",
            "**Decision:** ...",
            "**Alternatives considered:** ...",
            "**Why:** ...",
            "**Consequences:** ...",
            "-->",
        ]
    return "\n".join(lines)


def _section_4_glossary(driver: Driver, repo_id: str) -> str:
    terms = _q(driver,
        """
        MATCH (g:GlossaryTerm {repo_id: $rid})
        RETURN g ORDER BY g.term
        """,
        rid=repo_id)

    lines = ["## 4. Domain Glossary  [HUMAN REQUIRED]", "",
             "| Term | What it means here | Common misconception |",
             "|------|--------------------|----------------------|"]

    if terms:
        for row in terms:
            g = row["g"]
            lines.append(f"| **{g.get('term')}** | {g.get('definition', '...')} | {g.get('misconception', '—')} |")
    else:
        lines += [
            "| <!-- Term --> | <!-- Definition --> | <!-- Common misconception --> |",
            "",
            "> No glossary terms defined yet. Add domain-specific terminology via the Architecture Console.",
            "> Focus on words whose meaning in this codebase differs from common usage.",
        ]
    return "\n".join(lines)


def _section_5_invariants(driver: Driver, repo_id: str) -> str:
    policies = _q(driver,
        """
        MATCH (ap:ArchPolicy)-[:TARGETS]->(mod:Module)
        WHERE ap.status = 'active'
        RETURN ap.title AS title, ap.natural_language AS rule,
               ap.severity AS severity, mod.module_id AS module
        ORDER BY ap.severity DESC, mod.module_id
        """)

    lines = ["## 5. Per-Module Invariants  [AUTO + HUMAN]", ""]

    if policies:
        by_module: dict[str, list[dict]] = {}
        for p in policies:
            by_module.setdefault(p["module"], []).append(p)
        for module, rules in sorted(by_module.items()):
            lines.append(f"**`{module}`**")
            for r in rules:
                icon = "🚫" if r["severity"] == "error" else "⚠️" if r["severity"] == "warning" else "ℹ️"
                lines.append(f"- {icon} {r['rule']}")
            lines.append("")
    else:
        lines += [
            "> No architectural policies defined yet.",
            "> Define them via the Architecture Console — they are enforced automatically on every commit.",
        ]
    return "\n".join(lines)


def _section_6_data_models(driver: Driver, repo_id: str) -> str:
    # Find entity classes: annotated with @Entity, @Document, @Table, or named *Entity/*Model/*DTO
    entities = _q(driver,
        """
        MATCH (c:Class {repo_id: $rid})
        WHERE any(a IN c.annotations WHERE a CONTAINS 'Entity' OR a CONTAINS 'Document' OR a CONTAINS 'Table')
           OR c.name ENDS WITH 'Entity'
           OR c.name ENDS WITH 'Model'
        RETURN c.fqn AS fqn, c.name AS name, c.annotations AS annotations
        ORDER BY c.name
        LIMIT 30
        """,
        rid=repo_id)

    lines = ["## 6. Data Models  [AUTO]", ""]

    if not entities:
        lines.append("> No entity/document classes detected yet. Run a full scan to populate this section.")
        return "\n".join(lines)

    for e in entities:
        fqn = e["fqn"]
        lines.append(f"### `{e['name']}`")
        lines.append(f"FQN: `{fqn}`")
        if e.get("annotations"):
            lines.append(f"Annotations: {', '.join(e['annotations'][:5])}")
        lines.append("")

        # Fields
        fields = _q(driver,
            """
            MATCH (c {fqn: $fqn})-[:CONTAINS]->(f:Field)
            RETURN f.name AS name, f.type_name AS type_name, f.modifiers AS modifiers
            ORDER BY f.name
            """,
            fqn=fqn)
        if fields:
            lines.append("```")
            for f in fields:
                mods = " ".join(f.get("modifiers") or [])
                lines.append(f"  {mods + ' ' if mods else ''}{f.get('type_name', '?')} {f['name']}")
            lines.append("```")
        lines.append("")

    return "\n".join(lines)


def _section_7_api_surface(driver: Driver, repo_id: str) -> str:
    endpoints = _q(driver,
        """
        MATCH (e:ApiEndpoint {repo_id: $rid})
        RETURN e.http_method AS method, e.path AS path,
               e.handler_class AS handler, e.handler_method AS handler_method,
               e.request_body_type AS request_body, e.response_type AS response_type
        ORDER BY e.path, e.http_method
        """,
        rid=repo_id)

    lines = ["## 7. API Surface  [AUTO]", ""]

    if not endpoints:
        lines.append("> No REST endpoints detected yet. The extractor looks for Spring MVC and JAX-RS annotations.")
        return "\n".join(lines)

    # Group by handler class
    by_class: dict[str, list[dict]] = {}
    for ep in endpoints:
        by_class.setdefault(ep["handler"], []).append(ep)

    for cls, eps in sorted(by_class.items()):
        class_name = cls.split(".")[-1]
        lines.append(f"### `{class_name}`")
        lines.append(f"FQN: `{cls}`")
        lines.append("")
        lines.append("```")
        for ep in eps:
            rb = f"  ← {ep['request_body']}" if ep.get("request_body") else ""
            rt = f"  → {ep['response_type']}" if ep.get("response_type") else ""
            lines.append(f"{ep['method']:<8} {ep['path']}{rb}{rt}")
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def _section_8_concurrency(driver: Driver, repo_id: str) -> str:
    pools = _q(driver,
        """
        MATCH (tp:ThreadPool {repo_id: $rid})
        RETURN tp.class_fqn AS class_fqn, tp.field_name AS field_name,
               tp.pool_type AS pool_type, tp.configuration AS config
        ORDER BY tp.class_fqn
        """,
        rid=repo_id)

    async_methods = _q(driver,
        """
        MATCH (am:AsyncMethod {repo_id: $rid})
        RETURN am.class_fqn AS class_fqn, am.method_name AS method_name,
               am.mechanism AS mechanism, am.return_type AS return_type
        ORDER BY am.mechanism, am.class_fqn
        LIMIT 30
        """,
        rid=repo_id)

    facts = _q(driver,
        """
        MATCH (cf:ConcurrencyFact {repo_id: $rid})
        RETURN cf.class_fqn AS class_fqn, cf.fact_type AS fact_type, cf.detail AS detail
        ORDER BY cf.fact_type, cf.class_fqn
        LIMIT 30
        """,
        rid=repo_id)

    lines = ["## 8. Concurrency Model  [AUTO]", ""]

    if not any([pools, async_methods, facts]):
        lines.append("> No concurrency patterns detected yet.")
        return "\n".join(lines)

    if pools:
        lines += ["### Thread Pools", "", "| Class | Field | Type | Configuration |",
                  "|-------|-------|------|---------------|"]
        for p in pools:
            cls = p["class_fqn"].split(".")[-1]
            lines.append(f"| `{cls}` | `{p['field_name']}` | `{p['pool_type']}` | {p.get('config') or '—'} |")
        lines.append("")

    if async_methods:
        lines += ["### Async Methods", "", "| Mechanism | Class | Method | Return Type |",
                  "|-----------|-------|--------|-------------|"]
        for a in async_methods:
            cls = a["class_fqn"].split(".")[-1]
            lines.append(f"| `{a['mechanism']}` | `{cls}` | `{a['method_name']}` | `{a.get('return_type') or '?'}` |")
        lines.append("")

    if facts:
        lines += ["### Thread Safety Annotations & Synchronization", ""]
        for f in facts:
            cls = f["class_fqn"].split(".")[-1]
            lines.append(f"- `{cls}` — {f['fact_type']}" + (f": {f['detail']}" if f.get("detail") else ""))
        lines.append("")

    return "\n".join(lines)


def _section_9_build(driver: Driver, repo_id: str) -> str:
    bi = _q(driver,
        "MATCH (r:Repository {repo_id: $rid}) RETURN r.build_tool AS bt, r.java_version AS jv, r.test_framework AS tf, r.build_commands AS bc, r.key_dependencies AS deps",
        rid=repo_id)

    lines = ["## 9. Build & Test  [AUTO]", ""]

    if not bi or not bi[0].get("bt"):
        lines.append("> Build info not yet extracted.")
        return "\n".join(lines)

    b = bi[0]
    bt = b.get("bt", "?")
    tf = b.get("tf", "junit5")
    jv = b.get("jv", "?")

    lines += [
        f"**Build tool:** {bt}",
        f"**Java version:** {jv}",
        f"**Test framework:** {tf}",
    ]

    if b.get("deps"):
        lines += ["", "**Key dependencies:**"]
        for dep in (b["deps"] or []):
            lines.append(f"- {dep}")

    cmds = b.get("bc") or {}
    if cmds:
        lines += ["", "**Common commands:**", "", "```bash"]
        for label, cmd in cmds.items():
            lines.append(f"# {label}")
            lines.append(cmd)
        lines.append("```")

    # Test categories
    cats = _q(driver,
        """
        MATCH (tc:TestCategory {repo_id: $rid})
        RETURN tc.annotation AS annotation, tc.description AS description,
               tc.base_class AS base_class, tc.example_classes AS examples
        ORDER BY tc.annotation
        """,
        rid=repo_id)

    if cats:
        lines += ["", "**Test categories:**", ""]
        for c in cats:
            lines.append(f"- `{c['annotation']}` — {c['description']}")
            if c.get("base_class"):
                lines.append(f"  Base class: `{c['base_class']}`")
            if c.get("examples"):
                ex = c["examples"][:2]
                lines.append(f"  Examples: {', '.join('`' + e.split('.')[-1] + '`' for e in ex)}")

    return "\n".join(lines)


def _section_9b_freshness(driver: Driver, repo_id: str) -> str:
    rows = _q(driver,
        """
        MATCH (r:Repository {repo_id: $rid})
        RETURN r.last_commit AS last_commit,
               r.prov_freshness_ts AS freshness_ts,
               r.prov_commit_sha AS prov_commit,
               r.prov_confidence AS confidence,
               r.prov_source_tool AS source_tool
        """,
        rid=repo_id)
    if not rows:
        return ""
    r = rows[0]

    lines = ["## 9b. Knowledge Graph Provenance  [AUTO]", ""]
    lines += [
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Last indexed commit | `{r.get('last_commit', 'unknown')}` |",
        f"| Index freshness | {r.get('freshness_ts', 'unknown')} |",
        f"| Indexing tool | {r.get('source_tool', 'tree-sitter-java')} |",
        f"| Confidence | {r.get('confidence', 0.85):.0%} |",
        "",
        "> Stale nodes (written at an earlier commit) can be identified via `GET /provenance/{repo_id}`.",
        "> The watcher service re-indexes on every new commit automatically.",
    ]
    return "\n".join(lines)


def _section_10_working_style() -> str:
    return """## 10. Working Style Preferences  [HUMAN REQUIRED]

> How your team wants AI coding tools to behave in this codebase.
> Fill this in once — it is injected into every coding tool session.

**Scope:** <!-- e.g. Stay focused on the task. Do not refactor unrelated code. -->

**Decisions:** <!-- e.g. Give a recommendation with one-line reason rather than listing options. -->

**Breaking changes:** <!-- e.g. Always call out explicitly if a change touches the public API. -->

**Tests:** <!-- e.g. Every bug fix needs a test that would have caught the bug. -->

**Never do without asking:**
<!-- List specific actions that require explicit approval, e.g.:
- Change thread pool configuration
- Modify database schema
- Remove a public API endpoint
-->"""


def _section_11_known_issues(driver: Driver, repo_id: str) -> str:
    issues = _q(driver,
        "MATCH (ki:KnownIssue {repo_id: $rid}) RETURN ki ORDER BY ki.status",
        rid=repo_id)

    lines = ["## 11. Known Issues & Active Work  [HUMAN REQUIRED]", "",
             "| Issue | Status | Notes |",
             "|-------|--------|-------|"]

    if issues:
        for row in issues:
            ki = row["ki"]
            lines.append(f"| {ki.get('title', '?')} | {ki.get('status', '?')} | {ki.get('notes', '—')} |")
    else:
        lines += [
            "| <!-- Describe the issue --> | <!-- Known / In progress / Deferred --> | <!-- Context and workarounds --> |",
            "",
            "> No known issues recorded. Add them via the Architecture Console.",
        ]
    return "\n".join(lines)


def _section_12_pitfalls() -> str:
    return """## 12. Common Pitfalls  [HUMAN REQUIRED]

> Things that have burned people before. Read this before touching anything.

<!-- Add pitfalls specific to this codebase, e.g.:
- **Changing X requires Y** — explain the non-obvious dependency
- **Never call Z from thread pool W** — explain why
- **This field is not what it looks like** — explain the gotcha
-->"""


def _footer() -> str:
    return f"---\n*Generated by CodeKG — {datetime.utcnow().strftime('%Y-%m-%d')}. Update by pushing to the repo or editing in the Architecture Console.*"
